# 服务配置
server:
  port: 9999
  servlet:
    context-path: /

spring:

  # 文件上传大小
  servlet:
    multipart:
      max-request-size: 20000MB
      max-file-size: 20000MB

  # thymeleaf 配置
  thymeleaf:
    cache: false
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/

  # Mysql数据源 配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.131.130:3306/file_boot?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid
    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper


# mybatis-plus 配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.pepsiwyl.pojo
  mapper-locations: classpath*:/mapper/**/*.xml